
# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev23"
    fname: "23 Carlo main"

# -----------------------------------------------

homeassistant:
  customize:
    light.dev23:
      friendly_name: "Carlo main"

# -----------------------------------------------

input_boolean:
  carlo_switch_lock:
    name: Carlo light lock
    initial: off
    icon: mdi:lock

# -----------------------------------------------

binary_sensor:
  - platform: mqtt
    state_topic: "dev23/r/button2s"
    name: "dev23_button2s"
  - platform: mqtt
    state_topic: "dev23/r/button3s"
    name: "dev23_button3s"

# -----------------------------------------------

