### touch bedroom
# SL
# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev24"
    fname: "24 Louisa Main"

# -----------------------------------------------

binary_sensor:
  - platform: mqtt
    state_topic: "dev24/r/button2s"
    name: "dev24_button2s"

# -----------------------------------------------

homeassistant:
  customize:
    light.dev24:
      friendly_name: "Louisa main"

