# -----------------------------------------------

homeassistant:
  customize:
    light.dev16:
      friendly_name: "Kitchen Island"
      retain: True
    binary_sensor.dev16_button:
      friendly_name: "Kitchen Island button"
    binary_sensor.dev16_button1s:
      friendly_name: "Kitchen Island button1s"
    binary_sensor.dev16_motion:
      friendly_name: "Kitchen Island motion"
      device_class: motion
    sensor.dev16_temperature:
      friendly_name: "Kitchen Island temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev16"
    fname: "16 Kitchen Island"
    
  - platform: mqtt
    state_topic: "dev16/r/uptime"
    name: "dev16_uptime"
    unit_of_measurement: "min"

binary_sensor:
  - platform: mqtt
    state_topic: "dev16/r/motion_5"
    name: "dev16_motion"

# -----------------------------------------------


