# -----------------------------------------------

homeassistant:
  customize:
    light.dev6:
      friendly_name: "Cherry"
      retain: True
      icon: "mdi:tree"
    binary_sensor.dev6_button:
      friendly_name: "Cherry button"
    binary_sensor.dev6_button1s:
      friendly_name: "Cherry button1s"
    binary_sensor.dev6_motion:
      friendly_name: "Cherry motion"
      device_class: motion
    sensor.dev6_temperature:
      friendly_name: "Cherry temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev6"
    fname: "06 Cherry"

# -----------------------------------------------
