# -----------------------------------------------

homeassistant:
  customize:
    light.dev1:
      friendly_name: "Louisa Tower"
      retain: True
    binary_sensor.dev1_button:
      friendly_name: "Louisa Tower button"
    binary_sensor.dev1_button1s:
      friendly_name: "Louisa Tower button1s"
    binary_sensor.dev1_motion:
      friendly_name: "Louisa Tower motion"
      device_class: motion
    sensor.dev1_temperature:
      friendly_name: "Louisa Tower temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev5"
    fname: "05 Louisa Tower"

# -----------------------------------------------
