# -----------------------------------------------

homeassistant:
  customize:
    light.dev37:
      friendly_name: "EM"
    binary_sensor.dev37_button:
      friendly_name: "EM button"
    binary_sensor.dev37_button1s:
      friendly_name: "EM button1s"
    binary_sensor.dev37_motion:
      friendly_name: "EM motion"
      device_class: motion
    sensor.dev37_temperature:
      friendly_name: "EM temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"
    sensor.dev37_adc:
      friendly_name: "EM"
    sensor.dev37_em_cur:
      friendly_name: "EM current"
      unit_of_measurement: "W"
    sensor.dev37_em_cur_fast:
      friendly_name: "EM current fast"
      unit_of_measurement: "W"
    sensor.dev37_em_tot_grid:
      friendly_name: "EM total grid"
      unit_of_measurement: "kWh"
    sensor.dev37_em_tot_solar:
      friendly_name: "EM total solar"
      unit_of_measurement: "kWh"
    sensor.dev37_ads_ch0:
      friendly_name: "ADS CH0"
      unit_of_measurement: "mV"
    sensor.dev37_ads_ch1:
      friendly_name: "ADS CH1"
      unit_of_measurement: "mV"
    sensor.dev37_ads_ch2:
      friendly_name: "ADS CH2"
      unit_of_measurement: "mV"
    sensor.dev37_ads_ch3:
      friendly_name: "ADS CH3"
      unit_of_measurement: "mV"
    sensor.dev37_ads_ch4:
      friendly_name: "ADS CH4"
      unit_of_measurement: "mV"
    sensor.dev37_ads_ch5:
      friendly_name: "ADS CH5"
      unit_of_measurement: "mV"
    sensor.dev37_ads_ch6:
      friendly_name: "ADS CH6"
      unit_of_measurement: "mV"
    sensor.dev37_ads_ch7:
      friendly_name: "ADS CH7"
      unit_of_measurement: "mV"
    sensor.dev37_ads_ch8:
      friendly_name: "ADS CH8"
      unit_of_measurement: "mV"
    sensor.dev37_ads_ch9:
      friendly_name: "ADS CH9"
      unit_of_measurement: "mV"
    sensor.dev37_ads_ch10:
      friendly_name: "ADS CH10"
      unit_of_measurement: "mV"
    sensor.dev37_ads_ch11:
      friendly_name: "ADS CH11"
      unit_of_measurement: "mV"
# -----------------------------------------------

sensor:
# -------------- fake sensors for appdeamon ---------------

  - platform: mqtt
    state_topic: "dev37/r/energy_cost"
    name: "energy_cost"
# -----------------------------------------------

  - platform: template
    sensors: 
        dev37_ads_ch0_kw: 
           friendly_name: "00 Washing Machine"
           unit_of_measurement: 'W'
           value_template: "{{ [(((states('sensor.dev37_ads_ch0')|float)-(states('sensor.dev37_ads_ch7')|float)) * 0.66) | round(2), 0.00] | max }}"
        dev37_ads_ch1_kw: 
           friendly_name: "01 Garden drain pump"
           unit_of_measurement: 'W'
           value_template: "{{ [(((states('sensor.dev37_ads_ch1')|float)-(states('sensor.dev37_ads_ch7')|float)) * 0.66) | round(2), 0.00] | max }}"
        dev37_ads_ch2_kw: 
           friendly_name: "02 House drain pump + Beamer"
           unit_of_measurement: 'W'
           value_template: "{{ [(((states('sensor.dev37_ads_ch2')|float)-(states('sensor.dev37_ads_ch7')|float)) * 0.66) | round(2), 0.00] | max }}"
        dev37_ads_ch3_kw: 
           friendly_name: "03 Pool pump + WW Heater"
           unit_of_measurement: 'W'
           value_template: "{{ [(((states('sensor.dev37_ads_ch3')|float)-(states('sensor.dev37_ads_ch7')|float)) * 0.66) | round(2), 0.00] | max }}"
        dev37_ads_ch4_kw: 
           friendly_name: "04 ADS CH4"
           unit_of_measurement: 'W'
           value_template: "{{ [(((states('sensor.dev37_ads_ch4')|float)-(states('sensor.dev37_ads_ch7')|float)) * 0.66) | round(2), 0.00] | max }}"
        dev37_ads_ch5_kw: 
           friendly_name: "05 ADS CH5"
           unit_of_measurement: 'W'
           value_template: "{{ [(((states('sensor.dev37_ads_ch5')|float)-(states('sensor.dev37_ads_ch7')|float)) * 0.66) | round(2), 0.00] | max }}"
        dev37_ads_ch6_kw: 
           friendly_name: "06 ADS CH6"
           unit_of_measurement: 'W'
           value_template: "{{ [(((states('sensor.dev37_ads_ch6')|float)-(states('sensor.dev37_ads_ch7')|float)) * 0.66) | round(2), 0.00] | max }}"
        dev37_ads_ch7_kw: 
           friendly_name: "07 Ref measurement"
           unit_of_measurement: 'W'
           value_template: "{{ [(((states('sensor.dev37_ads_ch7')|float)-(states('sensor.dev37_ads_ch7')|float)) * 0.66) | round(2), 0.00] | max }}"
        dev37_ads_ch8_kw: 
           friendly_name: "08 Garage Back"
           unit_of_measurement: 'W'
           value_template: "{{ [(((states('sensor.dev37_ads_ch8')|float)-(states('sensor.dev37_ads_ch7')|float)) * 0.66) | round(2), 0.00] | max }}"
        dev37_ads_ch9_kw: 
           friendly_name: "09 C. Office, Hallway"
           unit_of_measurement: 'W'
           value_template: "{{ [(((states('sensor.dev37_ads_ch9')|float)-(states('sensor.dev37_ads_ch7')|float)) * 0.66) | round(2), 0.00] | max }}"
        dev37_ads_ch10_kw: 
           friendly_name: "10 C. Bath, Gym"
           unit_of_measurement: 'W'
           value_template: "{{ [(((states('sensor.dev37_ads_ch10')|float)-(states('sensor.dev37_ads_ch7')|float)) * 0.66) | round(2), 0.00] | max }}"
        dev37_ads_ch11_kw: 
           friendly_name: "11 Pool Heater"
           unit_of_measurement: 'W'
           value_template: "{{ [(((states('sensor.dev37_ads_ch11')|float)-(states('sensor.dev37_ads_ch7')|float)) * 0.66) | round(2), 0.00] | max }}"

# -----------------------------------------------
  - platform: mqtt_jkw
    name: "dev37"
    fname: "37 EM"

# -------------- fake sensors for appdeamon ---------------

  - platform: mqtt
    state_topic: "dev37/r/energy_cost"
    name: "energy_cost"
# -----------------------------------------------

  - platform: statistics
    entity_id: sensor.dev37_em_cur
    name: dev37_em_stst
    sampling_size: 1440
