####### VALUE WILL BE OVERRIDDEN BY APPDAEMON ANYWAY ##############

binary_sensor:
  - platform: template
    sensors:
      sec_short:
        value_template: "on"


sensor:
  - platform: template
    sensors:
# ---------------------------------------------------------
      g_motion_t:
        value_template: "loading"
      g_motion_cellar_t:
        value_template: "loading"
      g_motion_basement_t:
        value_template: "loading"
      g_motion_upstairs_t:
        value_template: "loading"
# ---------------------------------------------------------
      illuminum_kolja_t:
        value_template: "loading"
      illuminum_caro_t:
        value_template: "loading"
# ---------------------------------------------------------
      note:
        value_template: "loading"
      error:
        value_template: " "
# ---------------------------------------------------------
      sec_long:
        value_template: "loading"
# ---------------------------------------------------------
      zero:
        value_template: "0"
# ---------------------------------------------------------
      house_power_rem:
        value_template: "{{ ((states('sensor.pv_power_int')|float) +(states('sensor.dev37_em_cur_fast')|float) -(states('sensor.dev37_ads_ch0_kw')|float) -(states('sensor.dev37_ads_ch1_kw')|float) -(states('sensor.dev37_ads_ch2_kw')|float) -(states('sensor.dev37_ads_ch3_kw')|float) -(states('sensor.dev37_ads_ch4_kw')|float) -(states('sensor.dev37_ads_ch5_kw')|float) -(states('sensor.dev37_ads_ch6_kw')|float) -(states('sensor.dev37_ads_ch7_kw')|float) -(states('sensor.dev37_ads_ch8_kw')|float) -(states('sensor.dev37_ads_ch9_kw')|float) -(states('sensor.dev37_ads_ch10_kw')|float) -(states('sensor.dev37_ads_ch11_kw')|float)+0.01)| round(2) }}"
        unit_of_measurement: "W"
      house_power:
        value_template: "{{ ((states('sensor.pv_power_int')|float) +(states('sensor.dev37_em_cur_fast')|float)+0.01)| round }}"
        unit_of_measurement: "W"
# ---------------------------------------------------------
      bed_occupancy:
        value_template: >-
          {% if states('sensor.dev45_hx711')|float >1600000 %}
             2
          {% elif states('sensor.dev45_hx711')|float > 500000 %}
             1
          {% else %}
             0
          {% endif %}
# ---------------------------------------------------------
      money_in:
        value_template: "{{'{:.2f}'.format(((states('sensor.energy_calc_solar_to_grid_kwh')|float+states('sensor.burn_energy')|float)*0.08 + ((states('sensor.energy_calc_solar_to_home_kwh') | float)-(states('sensor.burn_energy')|float)) * 0.2534))  }}"
      money_out:
        value_template: "{{'{:.2f}'.format(((states('sensor.energy_calc_grid_to_home_kwh')|float)*0.2534+0.528064516))}}"
      money_today:
        value_template: "{{'{:.2f}'.format((states('sensor.money_out')|float)-(states('sensor.money_in')|float))}}"
# ---------------------------------------------------------     
  - platform: mqtt ### LED dimmer
    name: "pool_temp"
    state_topic: "pool_temp"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    device_class: "temperature"
# ---------------------------------------------------------


input_boolean:
  clear_error:
    name: "Clear error"
    initial: off
  clear_note:
    name: "Clear note"
    initial: off
  on_with_music:
    name: "on w/ music"
    initial: off
  sleep:
    name: "sleep"
    initial: off


homeassistant:
  customize:
    binary_sensor.sec_short:
      icon: "mdi:lock"
      device_class: "lock"
      friendly_name: "Security System"
    sensor.pool_temp:
      friendly_name: "Stable Pool temperature"
    sensor.zero:
      friendly_name: "Zero"
